/*
SQLyog Ultimate v10.51 
MySQL - 5.7.11-log 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `sys_authority_info` (
	`f_module_id` varchar (150),
	`f_allow_delete` int (11),
	`f_allow_edit` int (11),
	`f_allow_expand` int (11),
	`f_create_date` datetime ,
	`f_create_user_id` varchar (150),
	`f_create_user_name` varchar (150),
	`f_delete_mark` int (11),
	`f_description` varchar (600),
	`f_en_code` varchar (150),
	`f_enabled_mark` int (11),
	`f_full_name` varchar (120),
	`f_icon` varchar (120),
	`f_is_menu` int (11),
	`f_is_public` int (11),
	`f_modify_date` datetime ,
	`f_modify_user_id` varchar (150),
	`f_modify_user_name` varchar (300),
	`f_parent_id` varchar (150),
	`f_sort_code` int (11),
	`f_target` varchar (60),
	`f_url_address` varchar (6000)
); 
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('1',NULL,NULL,'1',NULL,'System','超级管理员','0',NULL,'DatabaseManage','1','数据管理','fa  fa-database','0','0',NULL,'','佘赐雄','2c90838f57c6e02e0157c729a9630045','0','expand','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('10',NULL,NULL,'1',NULL,NULL,NULL,'0',NULL,'UserManage','1','用户管理','fa  fa-user','1','0',NULL,'System','超级管理员','yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy','8','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('11',NULL,NULL,'1',NULL,NULL,NULL,'0',NULL,'RoleManage','1','角色管理','fa  fa-paw','1','0',NULL,'System','超级管理员','yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy','3','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('12',NULL,NULL,'1',NULL,NULL,NULL,'0',NULL,'JobManage','1','职位管理','fa fa-briefcase','1','0',NULL,'System','超级管理员','yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy','6','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('13',NULL,NULL,'1',NULL,NULL,NULL,'0',NULL,'PostManage','1','岗位管理','fa  fa-graduation-cap','1','0',NULL,'System','超级管理员','yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy','5','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('14',NULL,NULL,'1',NULL,NULL,NULL,'0',NULL,'UserGroupManage','1','用户组管理','fa  fa-group','1','0',NULL,'System','超级管理员','yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy','7','iframe','http://www.runoob.com/');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('15E2530EFC1CCC0D5F21A4CA5C78A426',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'baidu','baidu','1','百度','fa  fa-desktop',NULL,NULL,NULL,'','','DE55D6EDD28FC0AA058608C1E4B9F88C','0','iframe','http://www.baidu.com');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('16d4e2d5-d154-455f-94f7-63bf80ab26aa',NULL,NULL,'1',NULL,'0f36148c-719f-41e0-8c8c-16ffbc40d0e0','佘赐雄','0','客户基础资料','ClientBaseData','1','应用场景','fa fa-book','0','1',NULL,'System','超级管理员','0','1','expand','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('1c90838f57c6e02e0157c729a95c0043',NULL,NULL,'0',NULL,NULL,NULL,'0','系统导航功能','SystemModule','1','系统功能','fa  fa-navicon','1','0',NULL,'System','超级管理员','zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz','0','iframe','system/system_function_ztree.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a86b000b',NULL,NULL,'1',NULL,'System','超级管理员','0','动态链接数据库','DataBaseLink','1','数据库连接','fa  fa-plug','1','0',NULL,'System','超级管理员','2c90838f57c6e02e0157c729a9630045','2','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a871000c',NULL,NULL,'1',NULL,'System','超级管理员','0',NULL,'发起流程','1','发起流程','fa  fa-edit','1','0',NULL,'1','佘赐雄','5','1','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a876000d',NULL,NULL,'0',NULL,'System','超级管理员','0',NULL,'企业号设置','1','企业号设置','fa  fa-plug','1','0',NULL,'System','超级管理员','b9f9df92-8ac5-46e2-90ac-68c5c2e034c3','1','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a87b000e',NULL,NULL,'1',NULL,'System','超级管理员','0',NULL,'formCategory','1','表单类别','fa  fa-tags','1','0',NULL,'System','超级管理员','458113c6-b0be-4d6f-acce-7524f4bc3e88','1','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8850010',NULL,NULL,'0',NULL,'System','超级管理员','0','报表模板管理','ReportTemp','1','报表管理','fa  fa-cogs','1','1',NULL,'System','超级管理员','6','1','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a88a0011',NULL,NULL,'1',NULL,'System','超级管理员','0',NULL,'NewManage','1','新闻中心','fa  fa-feed','1','0',NULL,'System','超级管理员','4','1','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a88f0012',NULL,NULL,'0',NULL,'0f36148c-719f-41e0-8c8c-16ffbc40d0e0','佘赐雄','0','销售产品信息','Client_ProductInfo','1','场景1 数据库配置','fa  fa-shopping-bag','1','0',NULL,'1','佘赐雄','16d4e2d5-d154-455f-94f7-63bf80ab26aa','0','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8940013',NULL,NULL,'1',NULL,'System','超级管理员','0',NULL,'flowMonitor','1','流程监控','fa  fa-eye','1','0',NULL,'System','超级管理员','b5cb98f6-fb41-4a0f-bc11-469ff117a411','2','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8990014',NULL,NULL,'1',NULL,'System','超级管理员','0',NULL,'NoticeManage','1','通知公告','fa  fa-volume-up','1','0',NULL,'System','超级管理员','4','2','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a89d0015',NULL,NULL,'1',NULL,'0f36148c-719f-41e0-8c8c-16ffbc40d0e0','佘赐雄','0','商机管理','ClientChance','1','商机管理','fa  fa-binoculars','1','0',NULL,'System','超级管理员','ad147f6d-613f-4d2d-8c84-b749d0754f3b','2','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8a10016',NULL,NULL,'1',NULL,'0f36148c-719f-41e0-8c8c-16ffbc40d0e0','佘赐雄','0',NULL,'PurchaseReport','1','采购报表','fa  fa-bar-chart','1','0',NULL,'System','超级管理员','6','2','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8a50017',NULL,NULL,'0',NULL,'0f36148c-719f-41e0-8c8c-16ffbc40d0e0','佘赐雄','0',NULL,'Client_Trade','1','场景2 多种数据源迁移','fa  fa-tag','1','0',NULL,'1','佘赐雄','16d4e2d5-d154-455f-94f7-63bf80ab26aa','1','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8a90018',NULL,NULL,'0',NULL,'System','超级管理员','0',NULL,'企业号部门','1','企业号部门','fa  fa-sitemap','1','0',NULL,'System','超级管理员','b9f9df92-8ac5-46e2-90ac-68c5c2e034c3','2','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8ae0019',NULL,NULL,'1',NULL,'System','超级管理员','0',NULL,'flowCategory','1','流程类别','fa  fa-tags','1','0',NULL,'System','超级管理员','458113c6-b0be-4d6f-acce-7524f4bc3e88','2','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8b2001a',NULL,NULL,'1',NULL,'System','超级管理员','0','数据备份、数据还原','DataBaseBackup','1','数据库备份','fa  fa-cloud-download','1','0',NULL,'System','超级管理员','2c90838f57c6e02e0157c729a9630045','1','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8b6001b',NULL,NULL,'1',NULL,'System','超级管理员','0',NULL,'草稿流程','1','草稿流程','fa  fa-file-text-o','1','0',NULL,'24a055d6-5924-44c5-be52-3715cdd68011','陈彬彬','5','2','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8c2001e',NULL,NULL,'1',NULL,'System','超级管理员','0','通用数据字典','DataItemManage','1','通用字典','fa  fa-book','1','0',NULL,'System','超级管理员','CD162EA78B88EC492DF0DA1B87D35560','3','iframe','datacentor/addr/index.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8ca0020',NULL,NULL,'1',NULL,'System','超级管理员','0','自动产生号码','CodeRule','1','单据编码','fa  fa-barcode','1','0',NULL,'System','超级管理员','CD162EA78B88EC492DF0DA1B87D35560','4','iframe','http://www.baidu.com');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8d20022',NULL,NULL,'1',NULL,'System','超级管理员','0',NULL,'formDesign','1','表单设计','fa  fa-puzzle-piece','1','0',NULL,'System','超级管理员','458113c6-b0be-4d6f-acce-7524f4bc3e88','3','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8d60023',NULL,NULL,'0',NULL,'System','超级管理员','0',NULL,'企业号成员','1','企业号成员','fa  fa-users','1','0',NULL,'System','超级管理员','b9f9df92-8ac5-46e2-90ac-68c5c2e034c3','3','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8da0024',NULL,NULL,'0',NULL,'0f36148c-719f-41e0-8c8c-16ffbc40d0e0','佘赐雄','0',NULL,'Client_Sort','1','场景3 数据字段整理','fa  fa-tag','1','0',NULL,'1','佘赐雄','16d4e2d5-d154-455f-94f7-63bf80ab26aa','2','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8de0025',NULL,NULL,'1',NULL,'0f36148c-719f-41e0-8c8c-16ffbc40d0e0','佘赐雄','0',NULL,'SalesReport','1','销售报表','fa  fa-line-chart','1','0',NULL,'System','超级管理员','6','3','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8e20026',NULL,NULL,'1',NULL,'24a055d6-5924-44c5-be52-3715cdd68011','陈彬彬','0',NULL,'我的流程','1','我的流程','fa  fa-file-word-o','1','0',NULL,'24a055d6-5924-44c5-be52-3715cdd68011','陈彬彬','5','3','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8e60027',NULL,NULL,'0',NULL,'0f36148c-719f-41e0-8c8c-16ffbc40d0e0','佘赐雄','0','客户管理','ClientInfoManage','1','客户管理','fa  fa-suitcase','1','0',NULL,'System','超级管理员','ad147f6d-613f-4d2d-8c84-b749d0754f3b','3','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8ea0028',NULL,NULL,'1',NULL,'System','超级管理员','0','文件管理','ResourceFileManage','1','文件资料','fa  fa-jsfiddle','1','0',NULL,'System','超级管理员','2c90838f57c6e02e0157c729a9630045','4','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8ee0029',NULL,NULL,'1',NULL,'System','超级管理员','0','数据库表结构','DataBaseTable','1','数据表管理','fa  fa-table','1','0',NULL,'System','超级管理员','2c90838f57c6e02e0157c729a8da0024','0','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8f2002a',NULL,NULL,'1',NULL,'System','超级管理员','0',NULL,'flowDelegate','1','流程指派','fa  fa-random','1','0',NULL,'System','超级管理员','b5cb98f6-fb41-4a0f-bc11-469ff117a411','3','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8f6002b',NULL,NULL,'1',NULL,'0f36148c-719f-41e0-8c8c-16ffbc40d0e0','佘赐雄','0',NULL,'StorageReport','1','仓存报表','fa  fa-area-chart','1','0',NULL,'System','超级管理员','2c90838f57c6e02e0157c729a9630045','3','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8fa002c',NULL,NULL,'0',NULL,'0f36148c-719f-41e0-8c8c-16ffbc40d0e0','佘赐雄','0',NULL,'Client_Degree','1','场景4 桥数据处理','fa  fa-tag','1','0',NULL,'System','超级管理员','16d4e2d5-d154-455f-94f7-63bf80ab26aa','3','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a8ff002d',NULL,NULL,'0',NULL,'System','超级管理员','0','开票管理','ClientInvoice','1','客户开票','fa  fa-coffee','1','0',NULL,'System','超级管理员','ad147f6d-613f-4d2d-8c84-b749d0754f3b','4','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a903002e',NULL,NULL,'0',NULL,'System','超级管理员','0',NULL,'企业号应用','1','企业号应用','fa  fa-safari','1','0',NULL,'System','超级管理员','b9f9df92-8ac5-46e2-90ac-68c5c2e034c3','4','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a907002f',NULL,NULL,'1',NULL,'System','超级管理员','0',NULL,'flowDesign','1','流程设计','fa  fa-share-alt','1','0',NULL,'System','超级管理员','458113c6-b0be-4d6f-acce-7524f4bc3e88','4','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a90b0030',NULL,NULL,'1',NULL,'System','超级管理员','0',NULL,'待办流程','1','待办流程','fa  fa-hourglass-half','1','0',NULL,'24a055d6-5924-44c5-be52-3715cdd68011','陈彬彬','5','4','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a9210035',NULL,NULL,'1',NULL,'System','超级管理员','0',NULL,'已办流程','1','已办流程','fa  fa-flag','1','0',NULL,'System','超级管理员','5','5','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a9250036',NULL,NULL,'0',NULL,'0f36148c-719f-41e0-8c8c-16ffbc40d0e0','佘赐雄','0',NULL,'Client_Level','1','场景5 知识库整理','fa  fa-tag','1','0',NULL,'System','超级管理员','16d4e2d5-d154-455f-94f7-63bf80ab26aa','4','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a9290037',NULL,NULL,'1',NULL,'0f36148c-719f-41e0-8c8c-16ffbc40d0e0','佘赐雄','0','客户订单管理','ClientOrder','1','客户订单','fa  fa-modx','1','0',NULL,'System','超级管理员','ad147f6d-613f-4d2d-8c84-b749d0754f3b','5','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a9310039',NULL,NULL,'1',NULL,'0f36148c-719f-41e0-8c8c-16ffbc40d0e0','佘赐雄','0','现金银行报表','MoneyReport','1','对账报表','fa  fa-pie-chart','1','0',NULL,'System','超级管理员','6','5','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a936003a',NULL,NULL,'1',NULL,'System','超级管理员','0','邮件管理','EmailManage','1','邮件中心','fa  fa-send','1','0',NULL,'System','超级管理员','4','6','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a93a003b',NULL,NULL,'0',NULL,'System','超级管理员','0','日程管理','ScheduleManage','1','日程管理','fa  fa-calendar','1','0',NULL,'System','超级管理员','4','6','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a942003d',NULL,NULL,'0',NULL,'0f36148c-719f-41e0-8c8c-16ffbc40d0e0','佘赐雄','0',NULL,'Client_ChanceSource','1','场景6 特殊字段处理','fa  fa-tag','1','0',NULL,'1','佘赐雄','16d4e2d5-d154-455f-94f7-63bf80ab26aa','5','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a946003e',NULL,NULL,'0',NULL,'System','超级管理员','0','收款管理','ClienReceivable','1','收款管理','fa  fa-money','1','0',NULL,'System','超级管理员','ad147f6d-613f-4d2d-8c84-b749d0754f3b','6','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a94b003f',NULL,NULL,'1',NULL,'System','超级管理员','0',NULL,'工作委托','1','工作委托','fa  fa-coffee','1','0',NULL,'System','超级管理员','5','6','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a9540041',NULL,NULL,'1',NULL,'System','超级管理员','0','登录日志、操作日志。异常日志','SystemLog','1','系统日志','fa  fa-warning','1','0',NULL,'System','超级管理员','CD162EA78B88EC492DF0DA1B87D35560','5','iframe','https://www.oschina.net/');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a9600044',NULL,NULL,'1',NULL,'System','超级管理员','0','收款报表','ClienReceivableReport','1','收款报表','fa  fa-bar-chart','1','0',NULL,'System','超级管理员','ad147f6d-613f-4d2d-8c84-b749d0754f3b','7','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a9630045',NULL,NULL,'0',NULL,'0f36148c-719f-41e0-8c8c-16ffbc40d0e0','佘赐雄','0',NULL,'Client_ChancePhase','1','场景7 数据源（数据资产）管理','fa  fa-tag','1','0',NULL,'1','佘赐雄','16d4e2d5-d154-455f-94f7-63bf80ab26aa','6','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a96b0047',NULL,NULL,'1',NULL,'System','超级管理员','0','系统功能自定义表单','SystemForm','1','系统表单','fa  fa-paw','1','0',NULL,'System','超级管理员','CD162EA78B88EC492DF0DA1B87D35560','6','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a96f0048',NULL,NULL,'0',NULL,'System','超级管理员','0','支出管理','ClienExpenses','1','支出管理','fa  fa-credit-card-alt','1','0',NULL,'System','超级管理员','ad147f6d-613f-4d2d-8c84-b749d0754f3b','8','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a9730049',NULL,NULL,'0',NULL,'0f36148c-719f-41e0-8c8c-16ffbc40d0e0','佘赐雄','0',NULL,'Client_PaymentMode','1','场景8 批量处理','fa  fa-tag','1','0',NULL,'System','超级管理员','16d4e2d5-d154-455f-94f7-63bf80ab26aa','8','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a97b004b',NULL,NULL,'0',NULL,'System','超级管理员','0','自动生成代码、自动生成功能','CodeCreate','1','快速开发','fa  fa-code','1','0',NULL,'System','超级管理员','CD162EA78B88EC492DF0DA1B87D35560','1','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a982004d',NULL,NULL,'0',NULL,'24a055d6-5924-44c5-be52-3715cdd68011','陈彬彬','0','手机移动端开发','AppCreate','1','移动开发','fa  fa-file-code-o','1','0',NULL,'System','超级管理员','CD162EA78B88EC492DF0DA1B87D35560','7','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a986004e',NULL,NULL,'1',NULL,'System','超级管理员','0','收支报表','ClienCashBalanceReport','1','现金报表','fa  fa-bar-chart','1','0',NULL,'System','超级管理员','ad147f6d-613f-4d2d-8c84-b749d0754f3b','9','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a98a004f',NULL,NULL,'0',NULL,'eab01522-f4fe-48ce-8db6-76fd7813cdf5','刘晓雷','0',NULL,'rpt001','1','销售日报表','fa  fa-pie-chart','1','0',NULL,'System','超级管理员','6','9','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a98f0050',NULL,NULL,'0',NULL,'System','超级管理员','0',NULL,'Client_PaymentAccount','1','收支账户','fa  fa-tag','1','0',NULL,'System','超级管理员','ad147f6d-613f-4d2d-8c84-b749d0754f3b','8','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('2c90838f57c6e02e0157c729a9930051',NULL,NULL,'0',NULL,'System','超级管理员','0',NULL,'Client_ExpensesType','1','支出种类','fa  fa-tag','1','0',NULL,'System','超级管理员','ad147f6d-613f-4d2d-8c84-b749d0754f3b','9','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('4',NULL,NULL,'1',NULL,NULL,NULL,'0',NULL,'CommonInfo','1','公共信息','fa  fa-globe','0','0',NULL,'System','超级管理员','0','3','expand',NULL);
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('458113c6-b0be-4d6f-acce-7524f4bc3e88',NULL,NULL,'1',NULL,'System','超级管理员','0',NULL,'流程配置','1','流程配置','fa  fa-wrench','0','0',NULL,'24a055d6-5924-44c5-be52-3715cdd68011','陈彬彬','5','7','expand','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('5',NULL,NULL,'1',NULL,NULL,NULL,'0',NULL,'flowManage','1','工作流程','fa  fa-share-alt','0','0',NULL,'System','超级管理员','yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy','5','expand',NULL);
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('555D4B098704FEC63676E1663CC69F29',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','',NULL,'弹道','fa  fa-desktop',NULL,NULL,NULL,'','','7B7A686D52C5483EE7E59747AA10DA34','1','iframe','http://192.168.1.98:81/zentao/user-login-L3plbnRhby8=.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('5E62534C4E4BBA27082F71C6F7F985D6',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','',NULL,'西检平台','fa  fa-desktop',NULL,NULL,NULL,'','','7B7A686D52C5483EE7E59747AA10DA34','3','iframe','http://172.16.3.17:8080/ZHXXYYPT/new/page/zhcx/search.jsp');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('6',NULL,NULL,'1',NULL,NULL,NULL,'0',NULL,'ReportManage','1','报表中心','fa  fa-area-chart','0','0',NULL,'System','超级管理员','CD162EA78B88EC492DF0DA1B87D35560','0','expand',NULL);
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('665FF503A18E5635D96CCA3C91AFF301',NULL,NULL,NULL,NULL,'','',NULL,'','',NULL,'简书','fa  fa-desktop',NULL,NULL,NULL,NULL,NULL,'DE55D6EDD28FC0AA058608C1E4B9F88C','2','iframe','http://www.jianshu.com/');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('742E000245328C3F4BF2AE08FC1B859C',NULL,NULL,NULL,NULL,'','',NULL,'','',NULL,'图标集合','fa  fa-desktop',NULL,NULL,NULL,NULL,NULL,'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz','1','iframe','system/icons.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('7ae94059-9aa5-48eb-8330-4e2a6565b193',NULL,NULL,'1',NULL,'System','超级管理员','0','行政区域管理','AreaManage','1','行政区域','fa  fa-leaf','1','0',NULL,'System','超级管理员','CD162EA78B88EC492DF0DA1B87D35560','2','iframe','default.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('7B7A686D52C5483EE7E59747AA10DA34',NULL,NULL,NULL,NULL,'','',NULL,'','',NULL,'内网私服','fa  fa-desktop',NULL,NULL,NULL,NULL,NULL,'0','7','expand','http://www.jianshu.com/');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('8',NULL,NULL,'1',NULL,NULL,NULL,'0',NULL,'OrganizeManage','1','机构管理','fa  fa-sitemap','1','0',NULL,'System','超级管理员','2','1','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('9',NULL,NULL,'1',NULL,NULL,NULL,'0',NULL,'DepartmentManage','1','部门管理','fa  fa-th-list','1','0',NULL,'System','超级管理员','2','2','iframe','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('ad147f6d-613f-4d2d-8c84-b749d0754f3b',NULL,NULL,'1',NULL,'0f36148c-719f-41e0-8c8c-16ffbc40d0e0','佘赐雄','0','客户关系管理','CustomerManage','1','客户关系','fa  fa-briefcase','0','0',NULL,'System','超级管理员','0','5','expand',NULL);
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('b5cb98f6-fb41-4a0f-bc11-469ff117a411',NULL,NULL,'1',NULL,'System','超级管理员','0',NULL,'flowManage','1','流程管理','fa  fa-cogs','0','0',NULL,'24a055d6-5924-44c5-be52-3715cdd68011','陈彬彬','5','8','expand','error/404.html');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('b9f9df92-8ac5-46e2-90ac-68c5c2e034c3',NULL,NULL,'0',NULL,'System','超级管理员','0',NULL,'WeChatManage','1','微信管理','fa  fa-weixin','0','0',NULL,'System','超级管理员','0','4','expand','http://www.fenby.com/');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('CD162EA78B88EC492DF0DA1B87D35560',NULL,NULL,NULL,NULL,'','',NULL,'','',NULL,'其他','fa  fa-desktop',NULL,NULL,NULL,NULL,NULL,'0','1','expand','');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('DE55D6EDD28FC0AA058608C1E4B9F88C',NULL,NULL,NULL,NULL,'','',NULL,'','',NULL,'外网连接','fa  fa-desktop',NULL,NULL,NULL,NULL,NULL,'0','6','expand','');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('F407FC6275E88652F919FF3249E476BB',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','',NULL,'nexus','fa  fa-desktop',NULL,NULL,NULL,'','','7B7A686D52C5483EE7E59747AA10DA34','2','iframe','http://192.168.1.98:8082/nexus');
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',NULL,NULL,'1',NULL,NULL,NULL,'0',NULL,'BaseManage','1','单位组织','fa  fa-coffee','0','0',NULL,'1','佘赐雄','0','2','expand',NULL);
insert into `sys_authority_info` (`f_module_id`, `f_allow_delete`, `f_allow_edit`, `f_allow_expand`, `f_create_date`, `f_create_user_id`, `f_create_user_name`, `f_delete_mark`, `f_description`, `f_en_code`, `f_enabled_mark`, `f_full_name`, `f_icon`, `f_is_menu`, `f_is_public`, `f_modify_date`, `f_modify_user_id`, `f_modify_user_name`, `f_parent_id`, `f_sort_code`, `f_target`, `f_url_address`) values('zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',NULL,NULL,'1',NULL,NULL,NULL,'0',NULL,'SysManage','1','系统管理','fa  fa-desktop','0','0',NULL,'System','超级管理员','0','0','expand',NULL);
