CREATE OR REPLACE VIEW SYS_LRD_INFO AS
SELECT T.LRD_TASK_ID,
T.FILE_PATH,T.FILE_NAME,
M.TMP_TABLE_NAME,
M.TAB_STAT
FROM SYS_LRD_TASK T,SYS_LRD_TMP_TAB_MAP M
WHERE T.LRD_TASK_ID=M.LRD_TASK_ID
ORDER BY M.TMP_TABLE_NAME;
