CREATE OR REPLACE FUNCTION FUNC_GETDATE(P_VALUE IN NVARCHAR2, P_FORMAT IN NVARCHAR2)
RETURN DATE IS
BEGIN
       BEGIN
            RETURN TO_DATE(P_VALUE, P_FORMAT);
            EXCEPTION WHEN OTHERS THEN
            BEGIN
                      RETURN NULL;
            END;
       END;
END FUNC_GETDATE;
/
