CREATE OR REPLACE FUNCTION FUNC_EN16TO10(P_STR IN VARCHAR2)
  RETURN VARCHAR2 IS
  V_STR NUMBER(10) := 0;
BEGIN
  V_STR := TO_NUMBER(P_STR, 'XXXXXXXXXXX');
  RETURN TO_CHAR(V_STR);
  EXCEPTION WHEN OTHERS THEN
  BEGIN
      RETURN NULL;
  END;
END FUNC_EN16TO10;
/
