CREATE OR REPLACE FUNCTION SPLIT (P_LIST VARCHAR2,P_SEP VARCHAR2:=',')
RETURN TYPE_SPLIT PIPELINED IS
L_IDX PLS_INTEGER;
V_LIST VARCHAR2(4000):=P_LIST;
BEGIN
  LOOP
    L_IDX :=INSTR(V_LIST,P_SEP);
    IF L_IDX>0 THEN
      PIPE ROW(SUBSTR(V_LIST,1,L_IDX-1));
      V_LIST:= SUBSTR(V_LIST,L_IDX+LENGTH(P_SEP));
    ELSE
      PIPE ROW(V_LIST);
      EXIT;
    END IF;
  END LOOP;
  RETURN;
END SPLIT;
/
